// var word = "javascript";
// // word[0] = y;
// console.log(word);

/** we have two types of date type  
 -Primitive data types-- Strings__("")
                      -- Boolean__true/false
                      -- Number__ var number = 1; ** can de in decimal and other
                      -- Null__an enpty string
                      -- Undefined__a declared variable without a value
                      -- Symbol__A unique value that can be generated by Symbol constructor

-nonPrimitive data types -- Objects
                         --Arrays
                         --Function
 * */

//Numbers
var numRand = Math.random();
var calcs = numRand * 100;
var calc = Math.floor(calcs);

console.log(calc);

//String
var firstName = "Malik";
var lastName = "Akanni";
var country = "Nigeria";
var city = "Lagos";
var age = 23;
var isMarried = false;
var sister = "dami",
  brother = "hayatu",
  uncle = "yemi";
var quoteWithTick = `hello there "hayatu"`;

var stringConcat = firstName + " " + lastName + " " + "of" + " " + city; //String concatenation
console.log(stringConcat);

var helloWorld = `my name is ${firstName}`; // temperal lateral is used to get a value assigned to a variable.
console.log(helloWorld);

console.log(country.length);
